name: Deploy Azure SQL DB with Terraform and Restore

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    # 1. Clonar el repo
    - name: Checkout repo
      uses: actions/checkout@v2

    # 2. Configurar Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.4.6"

    # 3. Exportar credenciales de Azure para Terraform
    - name: Set Azure Credentials as environment variables
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

    # 4. Ir a la carpeta infra
    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Apply
      working-directory: ./infra
      run: terraform apply -auto-approve

    # 5. Login en Azure CLI

    
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    # 6. Instalar sqlcmd
    - name: Install sqlcmd
      run: |
        # Descargar clave de Microsoft
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

        # Configurar repositorio para Ubuntu 20.04 (no 24.04)
        sudo add-apt-repository "$(curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list)"

        # Instalar dependencias
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

        # Agregar al PATH
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc



    # 7. Restaurar base de datos usando restore.sql
    - name: Run SQL script to restore DB
      run: |
        /opt/mssql-tools/bin/sqlcmd -S tcp:${{ secrets.SQL_SERVER_NAME }}.database.windows.net -d ${{ secrets.DATABASE_NAME }} -U ${{ secrets.SQL_ADMIN }} -P "${{ secrets.SQL_PASSWORD }}" -i ./scripts/restore.sql
